"""empty message.

Revision ID: 265fa9b35d33
Revises: 4c759a96a7c3
Create Date: 2026-03-09 05:28:29.992751

"""


# revision identifiers, used by Alembic.
revision = "265fa9b35d33"
down_revision = "4c759a96a7c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
