"""empty message.

Revision ID: 7479bf23230c
Revises: f7c2a2f58213
Create Date: 2026-03-08 21:06:45.153362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7479bf23230c'
down_revision = 'f7c2a2f58213'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('sync_checksum', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('sync_checksum', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'sync_checksum')
    op.drop_column('columns', 'sync_checksum')
    # ### end Alembic commands ###
