"""empty message.

Revision ID: f7c2a2f58213
Revises: f8a66e3b1aa6
Create Date: 2026-03-08 20:54:21.312535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c2a2f58213'
down_revision = 'f8a66e3b1aa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
