"""cleanup_redundant_descriptions.

Revision ID: f8a66e3b1aa6
Revises: e7f8g9h1i2j3
Create Date: 2026-03-08 20:50:32.094539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a66e3b1aa6'
down_revision = 'e7f8g9h1i2j3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columns', 'description')
    op.drop_column('tables', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('columns', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
