"""empty message.

Revision ID: 337ff3445028
Revises: 7479bf23230c
Create Date: 2026-03-08 21:09:12.655577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337ff3445028'
down_revision = '7479bf23230c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
