"""empty message.

Revision ID: 4c759a96a7c3
Revises: 337ff3445028
Create Date: 2026-03-08 21:11:34.054516

"""


# revision identifiers, used by Alembic.
revision = "4c759a96a7c3"
down_revision = "337ff3445028"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
